version: "3.8"

services:
  app:
    build: .
    container_name: medical-record-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - medical-net

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: medicaldb
    ports:
      - "5432:5432"
    networks:
      - medical-net

networks:
  medical-net:
    driver: bridge
